export const routeNames = {
  "/home/dashboard/dashboardhome/0": "Dashboard",
  "/home/dailysales/dailysaleshome/0": "Daily Sales",
  "/home/mystation/mystationhome/0": "My Station",
  "/home/recordsales": "Record Sales",
  "/home/analysis/analysishome/0": "Analysis",
  "/home/lposales/lposaleshome/0": "Corporate Sales",
  "/home/lposales/corporatecustomer": "Corporate Customer",
  "/home/productorder": "Product Order",
  "/home/incomingorder": "Incoming Order",
  "/home/supply/supplyhome/0": "Supply",
  "/home/regulatory": "Regulatory",
  "/home/tankupdate": "Tank Update",
  "/home/hr/hrhome/0": "Human Resources",
  "/home/settings": "Settings",
};
